exports.getCate = async function getCate() {
  return [
    {
      uri: 'entertain/karaoke',
      name: 'karaoke',
      param: {},
      category_lv1_name: 'Karaoke',
      category_lv2_name: '',
      type: 'centers',
    },
    {
      uri: 'entertain/billiards',
      name: 'billiards',
      param: {},
      category_lv1_name: 'Billiards',
      category_lv2_name: '',
      type: 'centers',
    },
    {
      uri: 'entertain/giai-tri',
      name: 'giai-tri',
      param: {},
      category_lv1_name: 'Rạp chiếu phim',
      category_lv2_name: '',
      type: 'centers',
    },
    {
      uri: 'entertain/san-khau',
      name: 'san-khau',
      param: {},
      category_lv1_name: 'Sân khấu',
      category_lv2_name: '',
      type: 'centers',
    },
    {
      uri: 'entertain/khu-choi-game',
      name: 'khu-choi-game',
      param: {},
      category_lv1_name: 'Khu chơi game',
      category_lv2_name: '',
      type: 'centers',
    },
    {
      uri: 'shop/cua-hang',
      name: 'shop/cua-hang',
      param: {},
      category_lv1_name: 'Cửa hàng',
      category_lv2_name: '',
      type: 'places',
    },
    {
      uri: 'entertain/sieu-thi',
      name: 'sieu-thi',
      param: {},
      category_lv1_name: 'Siêu thị',
      category_lv2_name: '',
      type: 'places',
    },
    {
      uri: 'entertain/trung-tam-thuong-mai',
      name: 'trung-tam-thuong-mai',
      param: {},
      category_lv1_name: 'Trung tâm thương mại',
      category_lv2_name: '',
      type: 'places',
    },
    {
      uri: 'entertain/cho',
      name: 'cho',
      param: {},
      category_lv1_name: 'Chợ',
      category_lv2_name: '',
      type: 'places',
    },
    {
      uri: 'entertain/online-shopping',
      name: 'online-shopping',
      param: {},
      category_lv1_name: 'Online shopping',
      category_lv2_name: '',
      type: 'places',
    },
    {
      uri: 'travel/khu-du-lich',
      name: 'khu-du-lich',
      param: {},
      category_lv1_name: ' Thăm quan &amp; chụp ảnh',
      category_lv2_name: '',
      type: 'places',
    }, {
      uri: 'travel/khach-san',
      name: 'khach-san',
      param: {},
      category_lv1_name: 'Khách sạn',
      category_lv2_name: '',
      type: 'hotels',
    }, {
      uri: 'food/quan-nhau',
      name: 'quan-nhau',
      param: {},
      category_lv1_name: 'Quán nhậu/ bia hơi',
      category_lv2_name: '',
      type: 'restaurants',
    }, {
      uri: 'wedding/tiec-cuoi-hoi-nghi',
      name: 'tiec-cuoi-hoi-nghi',
      param: {},
      category_lv1_name: 'Trung tâm tiệc cưới/ hội nghị',
      category_lv2_name: '',
      type: 'places',
    }, {
      uri: 'food/beer-club',
      name: 'beer-club',
      param: {},
      category_lv1_name: 'Bar/ Pub/ Club',
      category_lv2_name: 'Bar/ Pub',
      type: 'restaurants',
    }, {
      uri: 'food/bar-pub',
      name: 'bar-pub',
      param: {},
      category_lv1_name: 'Bar/ Pub/ Club',
      category_lv2_name: 'Club / Beer',
      type: 'restaurants',
    }, {
      uri: 'food/dia-diem',
      param: { q: 'trà+sữa' },
      name: 'trà+sữa',
      category_lv1_name: 'Trà',
      category_lv2_name: 'Trà sữa',
      type: 'restaurants',
    }, {
      uri: 'food/dia-diem',
      param: { q: 'trà+chanh' },
      name: 'trà+chanh',
      category_lv1_name: 'Trà',
      category_lv2_name: 'Trà chanh / Trà đá',
      type: 'restaurants',
    }, {
      uri: 'food/buffet',
      name: 'buffet',
      param: {},
      category_lv1_name: 'Buffet / BBQ',
      category_lv2_name: '',
      type: 'restaurants',
    }, {
      uri: 'food/an-chay',
      name: 'an-chay',
      param: {},
      category_lv1_name: 'Ăn chay / thực dưỡng',
      category_lv2_name: '',
      type: 'restaurants',
    },
    // {
    //   uri: 'food/pizza',
    //   name: 'pizza',
    //   param: {},
    //   category_lv1_name: 'Đồ ăn nhanh',
    //   category_lv2_name: 'Pizza',
    //   type: 'restaurants',
    // },
    {
      uri: 'food/dia-diem',
      param: { q: 'gà+rán' },
      name: 'gà+rán',
      category_lv1_name: 'Đồ ăn nhanh',
      category_lv2_name: 'Gà rán',
      type: 'restaurants',
    }, {
      uri: 'food/dia-diem',
      param: { q: 'đồ+ăn+vặt' },
      name: 'đồ+ăn+vặt',
      category_lv1_name: 'Đồ ăn vặt',
      category_lv2_name: '',
      type: 'restaurants',
    }, {
      uri: 'food/tiem-banh',
      name: 'tiem-banh',
      param: {},
      category_lv1_name: 'Bánh ngọt / tráng miệng',
      category_lv2_name: '',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'phở' },
      name: 'phở',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Phở',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bún' },
      name: 'bún',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Bún',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'cháo' },
      name: 'cháo',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Cháo',
      type: 'restaurants',
    },

    {
      uri: 'food/dia-diem',
      param: { q: 'bánh+canh' },
      name: 'bánh+canh',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Bánh canh',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'miến' },
      name: 'miến',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Miến',
      type: 'restaurants',
    },


    {
      uri: 'food/dia-diem',
      param: { q: 'bánh+mì' },
      name: 'bánh+mì',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Bánh mì',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bánh+bao' },
      name: 'bánh+bao',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Bánh bao',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'mì+vằn+thắn' },
      name: 'mì+vằn+thắn',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Mì vằn thắn',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bánh+cuốn' },
      name: 'bánh+cuốn',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Bánh cuốn',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bún+chả' },
      name: 'bún+chả',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Bún chả',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'xôi' },
      name: 'xôi',
      category_lv1_name: 'Đồ ăn sáng',
      category_lv2_name: 'Xôi',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'lẩu' },
      name: 'lẩu',
      category_lv1_name: 'Quán ăn đêm',
      category_lv2_name: 'Lẩu',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bún' },
      name: 'bún',
      category_lv1_name: 'Quán ăn đêm',
      category_lv2_name: 'Bún phở',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'cháo' },
      name: 'cháo',
      category_lv1_name: 'Quán ăn đêm',
      category_lv2_name: 'Cháo',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bò+nướng' },
      name: 'bò+nướng',
      category_lv1_name: 'Quán ăn đêm',
      category_lv2_name: 'Nầm bò nướng',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'hủ+tiếu' },
      name: 'hủ+tiếu',
      category_lv1_name: 'Quán ăn đêm',
      category_lv2_name: 'Hủ tiếu',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'cơm+rang+mì+xào' },
      name: 'cơm+rang+mì+xào',
      category_lv1_name: 'Quán ăn đêm',
      category_lv2_name: 'Cơm rang/ mì xào',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'ốc' },
      name: 'ốc',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Ốc',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'nem+chua+rán' },
      name: 'nem+chua+rán',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Nem chua rán',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'thịt+xiên+nướng' },
      name: 'thịt+xiên+nướng',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Thịt xiên nướng',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bánh+tráng+trộn' },
      name: 'bánh+tráng+trộn',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Bánh tráng trộn/ nướng',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'chè' },
      name: 'chè',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Chè',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'nộm' },
      name: 'nộm',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Nộm',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'bánh+xèo' },
      name: 'bánh+xèo',
      category_lv1_name: 'Quán ăn vỉa hè',
      category_lv2_name: 'Bánh xèo',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'healthy' },
      name: 'healthy',
      category_lv1_name: 'Đồ ăn kiêng/ Healthy',
      category_lv2_name: 'Eat clean',
      type: 'restaurants',
    },
    {
      uri: 'food/dia-diem',
      param: { q: 'keto' },
      name: 'keto',
      category_lv1_name: 'Đồ ăn kiêng/ Healthy',
      category_lv2_name: 'Keto',
      type: 'restaurants',
    },
  ];
};
